# Binance Pump and Dump Alert Configuration

# Using Spot API with url set to https://api.binance.com/api/v3/ticker/price
# Using Futures API with url set to: https://fapi.binance.com/fapi/v1/ticker/price
apiUrl: https://api.binance.com/api/v3/ticker/price

# Intervals which are monitored. Add or remove intervals as you like.
chartIntervals:
  - 1m
  - 5m
  - 15m
  - 30m
  - 1h
  - 3h
  - 6h

# Values in % at which an alert is triggered. Ensure interval exists in chartIntervals as well.
outlierIntervals:
  "1s": 0.02
  "5s": 0.05
  "15s": 0.06
  "30s": 0.08
  "1m": 0.1
  "5m": 0.10
  "15m": 0.15
  "30m": 0.20
  "1h": 0.30
  "3h": 0.4
  "6h": 0.5

# Used for telegram bot updates

# Insert telegramToken obtained from @BotFather here
#telegramToken: '6552511028:AAFOWc_1Z5NqvdmDtPjCZJ9hp_r-R2aOXSw'
telegramToken: '5894885604:AAH5XD-0rQoi5zw23CaugRBJ45-EpbkCY88'
# Insert Chat ID obtained from @get_id_bot here
#telegramChatId: 6266505287 - Jeff Bezos Warrent
telegramChatId: 5833143227
# Insert Chat ID for top pump dump alert, if left on `0` it'll send the message to telegram chat id
#telegramAlertChatId: -1001720823065  AI 306 
#telegramAlertChatId: -1002068543523

telegramAlertChatId: -1001697199458

# Useful Params

# Interval between each price extract from Binance REST API
extractInterval: 1s

# Watchlist only mode, if enabled, ONLY pairs in watchlist will be monitored
# E.g. 'ADAUSDT', 'ETHUSDT'
# watchlist:
#  - ADAUSDT
#  - ETHUSDT

# Blacklist only mode, if enabled, pairs in blacklist will be IGNORED it DOES NOT IMPACT pairsOfInterest
blacklist:
  - NBTUSDT
  - BTTCUSDT
  - PERLUSDT
  - WTCUSDT
  - BTSUSDT
  - TORNUSDT
  - BCCUSDT
  - VENUSDT
  - NULSUSDT
  - PAXUSDT
  - NANOUSDT
  - BTTUSDT
  - MITHUSDT
  - TFUELUSDT
  - ERDUSDT
  - WINUSDT
  - GTOUSDT
  - COSUSDT
  - TOMOUSDT
  - DOCKUSDT
  - WANUSDT
  - FUNUSDT
  - BEAMUSDT
  - CTXCUSDT
  - TROYUSDT
  - VITEUSDT
  - WRXUSDT
  - LTOUSDT
  - MBLUSDT
  - DATAUSDT
  - HIVEUSDT
  - ARDRUSDT
  - VTHOUSDT
  - DCRUSDT
  - IRISUSDT
  - KMDUSDT
  - JSTUSDT
  - PAXGUSDT
  - WNXMUSDT
  - DIAUSDT
  - FIOUSDT
  - WINGUSDT
  - SUNUSDT
  - UTKUSDT
  - AUDIOUSDT
  - HARDUSDT
  - AVAUSDT
  - JUVUSDT
  - PSGUSDT
  - OGUSDT
  - ATMUSDT
  - ASRUSDT
  - FIROUSDT
  - DODOUSDT
  - ACMUSDT
  - FISUSDT
  - PONDUSDT
  - DEGOUSDT
  - RAMPUSDT
  - EPSUSDT
  - AUTOUSDT
  - TKOUSDT
  - PUNDIXUSDT
  - BTGUSDT
  - MIRUSDT
  - BARUSDT
  - FORTHUSDT
  - BURGERUSDT
  - POLSUSDT
  - MDXUSDT
  - NUUSDT
  - TORNUSDT
  - KEEPUSDT
  - ERNUSDT
  - PHAUSDT
  - MLNUSDT
  - DEXEUSDT
  - CLVUSDT
  - TVKUSDT
  - FARMUSDT
  - ALPACAUSDT
  - QUICKUSDT
  - MBOXUSDT
  - FORUSDT
  - REQUSDT
  - GHSTUSDT
  - TRIBEUSDT
  - GNOUSDT
  - ELFUSDT
  - POLYUSDT
  - VIDTUSDT
  - SYSUSDT
  - DFUSDT
  - FIDAUSDT
  - CVPUSDT
  - BETAUSDT
  - RAREUSDT
  - LAZIOUSDT
  - CHESSUSDT
  - ADXUSDT
  - RGTUSDT
  - CITYUSDT
  - KP3RUSDT
  - QIUSDT
  - PORTOUSDT
  - VGXUSDT
  - AMPUSDT
  - PLAUSDT
  - PYRUSDT
  - ALCXUSDT
  - SANTOSUSDT
  - MCUSDT
  - ANYUSDT
  - FLUXUSDT
  - VOXELUSDT
  - OOKIUSDT
  - LOKAUSDT
  - SCRTUSDT
  - ACAUSDT
  - ANCUSDT
  - XNOUSDT
  - ALPINEUSDT
  - NBTUSDT
  - KDAUSDT
  - BSWUSDT
  - BIFIUSDT
  - MULTIUSDT
  - MOBUSDT
  - NEXOUSDT
  - REIUSDT
  - EPXUSDT
  - NEBLUSDT
  - OSMOUSDT
  - RPLUSDT
  - PROSUSDT
  - GNSUSDT
  - SYNUSDT
  - VIBUSDT
  - BETHUSDT
  - PROMUSDT
  - QKCUSDT
  - UFTUSDT
  - OAXUSDT
  - WBTCUSDT
  - AERGOUSDT
  - ASTUSDT
  - WBETHUSDT
  - CREAMUSDT
  - GFTUSDT
  - IQUSDT
  - PIVXUSDT
  - VICUSDT
  - AEURUSDT
  - PDAUSDT
#  - ETHUSDT

# List the trading currency you are interested in. Other options include 'BUSD', 'BTC' , 'ETH'
pairsOfInterest:
  - USDT

# Feature params

# Determine whether to look at DUMPs
dumpEnabled: True

# Top Pump & Dump Feature Params

# Set to false if not interested in top pump info
topPumpEnabled: True
# Set to false if not interested in top dump info
topDumpEnabled: True
# Set to false if not interested in net movement of coins
additionalStatsEnabled: True
# Top X amount of coins shown in the interval report, adjust to show more or less within the timeframe
noOfReportedCoins: 5
# Intervals for top pump and dump to be sent, ensure its in chartIntervals + outlierIntervals as well
topReportIntervals:
  - 5m
  - 15m
  - 1h


# Define your own bot emojis.
botEmoji: ! "\U0001F916" # 🤖
pumpEmoji: ! "\U0001F7E2" # 🟢 or '\U0001F4C8' 📈 '\U0001F53C'🔼
dumpEmoji: ! "\U0001F534" # 🔴 or '\U0001F4C9' 📉 '\U0001F53D'🔽
#topEmoji: ! "\U0001F3C6" # 🏆
topEmoji: ! "\U0001f3af" # 🎯
newsEmoji: ! "\U0001F4F0" # 📰 or '\U0001F680' 🚀
copyrightEmoji: ! "\u00A9\uFE0F" # ©️ 

# Debug Params (Avoid touching it if there's no issues)

# If False we do not print unnecessary messages
debug: False
# Skip alert at higher timeframes when change in % did not change value by threshold in percentage points
alertSkipThreshold: 0.75
# Interval for clearing array to prevent memory can handle up to 12h+ depending on system
resetInterval: 6h
# In the case of get price fail, this is the time delay before re-attempt
priceRetryInterval: 5s
# Disables checking and adding of new listing pairs
checkNewListingEnabled: True
# Disables rounding to nearest hour for first TPD if false
topReportNearestHour: True

